apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rockyjr-git/simple-app-k8s.git
    # Specify your source details here
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ns
    # Specify your destination details here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
  syncWave:
    automated:
      syncWave: 1
  sync:
    period: 05s  # Set the sync time to 10 seconds
